<a href="https://colab.research.google.com/github/huyenbui117/practicePython/blob/main/Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c=a+b
c=c*a
c[2]

21

In [10]:
a=np.array([[1,2,3],[0,1,4]])
a.size

6

In [38]:
a=np.array([[1,2,3],[0,1,4]])
b=np.zeros((2,3), dtype=np.int16)
c=np.ones((2,3), dtype=np.int16)
d=a+b+c
d[1,2]
b
c

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [39]:
a=np.array([[0,1,0],[1,0,1]])
a+=3
b=a+3
a[1,2]+b[1,2]

11

In [17]:
a=np.array([[3,6,7],[5,-3,0]])
b=np.array([[1,1],[2,1],[3,-3]])
np.dot(a,b)

array([[ 36, -12],
       [ -1,   2]])

In [33]:
a=np.array([[1,4,5,12,14],
            [-5,8,9,0,17],
            [-6,7,11,19,21]])
a[:,2:4]

array([[ 5, 12],
       [ 9,  0],
       [11, 19]])

In [36]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)
a+3

array([3, 4])